name: qonversion_example
description: Demonstrates how to use the qonversion plugin.

version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  qonversion_flutter:
    path: ../

flutter:
  uses-material-design: true
