name: qonversion_flutter
description: In-App Purchase Flutter plugin to implement subscriptions and in app purchases. Simple way to validate user receipts and manage cross-platform user access to paid content on your app. Android and iOS
version: 3.2.1
homepage: 'https://qonversion.io'
repository: 'https://github.com/qonversion/flutter-sdk'

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.0.1
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.1
  json_serializable: ^4.1.0

flutter:
  plugin:
    platforms:
      android:
        pluginClass: QonversionFlutterSdkPlugin
        package: com.qonversion.flutter.sdk.qonversion_flutter_sdk
      ios:
        pluginClass: QonversionFlutterSdkPlugin
      macos:
        pluginClass: QonversionFlutterSdkPlugin
