name: qonversion_flutter
description: Powerful yet simple subscription analytics
version: 0.2.0
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.qonversion.flutter.sdk.qonversion_flutter_sdk
    pluginClass: QonversionFlutterSdkPlugin
